site_name: ada
nav:
    - Inicio: index.md
    - 1.- Entrada/Salida (I/O) de la información: 
      - 1.2.- java.IO: ud1/1io.md
    - About : about.md
theme:
  name: material
  language: es
  custom_dir: overrides
  #logo: assets/logo.png
  
  palette:
    - scheme: default
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  
  extra:
    #generator: false
  
  copyright: Copyright &copy; 2021 - Patricia Martí
  
  features:
    - content.code.annotate
    - navitagion.tabs
    #- navigation.sections
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:  
  analytics:
    provider: google
    property:
