site_name: Acceso a Datos
nav:
    - Inicio: index.md
    - 1.- Acceso a datos mediante ficheros: 
      - 1.1.- Gestión de ficheros con Java: ud1/filevsfiles.md
      - 1.2.- Lectura y escritura de ficheros en Java:
        - 1.2.1.- Introducción: ud1/io.md
        - 1.2.2.- Acceso secuencial:
          - Operaciones con ficheros binarios en Java: ud1/binaryfiles.md
          - Operaciones con ficheros de caracteres en Java: ud1/characterfiles.md
        - 1.2.3.- Acceso aleatorio:
          - Operaciones con ficheros de acceso aleatorio en Java: ud1/randomaccessfile.md
      - 1.3.- Recorrido de directorios con java.nio: ud1/fileswalk.md
      - 1.4.- Lectura y escritura de objectos en Java: ud1/serialization.md
      - 1.5.- Ficheros de propiedades en Java: ud1/propertiesfile.md
      - 1.6.- Ficheros JSON en Java: ud1/jsonfiles.md
      - 1.7.- Crear un .jar: ud1/createjar.md
      - 1.8.- try-with-resources: ud1/trywithresources.md
    - 2.- Acceso a bases de datos relacionales con JDBC:
      - 2.1.- Persistencia de la información: ud2/persistencia.md
      - 2.2.- Introducción a JDBC y conectores: ud2/mapeo.md
      - 2.3.- Fundamentos de JDBC: ud2/conectores.md
      - 2.4.- Definición de estructuras de BD y ejecución de sentencias DDL: ud2/ddl.md
      - 2.5.- Modificación de datos con JDBC (DML): ud2/dml.md
      - 2.6.- Consultas y manipulación de resultados con JDBC (DQL): ud2/dql.md
      - 2.7.- Procedimientos almacenados y CallableStatement: ud2/procedures.md
      - 2.8.- Gestión de transacciones en JDBC: ud2/transactions.md
      - 2.9.- Mejora del rendimiento y buenas prácticas: ud2/26rendimiento.md
      - 2.10.- Estructura de los proyectos: ud2/27projectstructure.md
    - 3.- ORM con Hibernate y JPA:
      - 3.1.- Herramientas ORM: ud3/31mapeo.md
      - 3.2.- Jakarta - JPA: ud3/32jpa.md
      - 3.3.- Hibernate: ud3/33hibernate.md
      - 3.4.- Patrón DAO: ud3/34dao.md
      - 3.5.- Service Layer: ud3/35service.md
    - 4.- Bases de datos documentales con MongoDB:
      - 4.1.- Introducción: udmongodb/mongodb1.md
    - 5.- Spring Framework:
      - 5.1.- Introducción a Spring Framework: ud4/41introduccionspring.md
      - 5.2.- Spring Data JPA: ud4/42repository.md
      - 5.3.- API REST - Spring Web: ud4/43rest.md
      - 5.4.- @Query y Response: ud4/44queryresponse.md
    - 6.- Java Modules:
      - 6.1.- Módulos en Java: ud5/51modulo.md
    - About : about.md
theme:
  name: material
  language: es
  custom_dir: overrides
  #logo: assets/logo.png
  
  palette:
    - scheme: default
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  
  extra:
    #generator: false
  
  copyright: Copyright &copy; 2021 - Patricia Martí
  
  features:
    - content.code.annotate
    - navitagion.tabs
    #- navigation.sections
    - navigation.top

markdown_extensions:
  - admonition                  # Info boxes (in different colors)
  - codehilite
  - pymdownx.details            # "
  - pymdownx.superfences        # Info boxes, tabs
  - pymdownx.caret              # Allow superscript and insertion marks (^ and ^^)
  - pymdownx.tilde              # Allow subscript and deletion marks (~ and ~~)
  - pymdownx.keys               # Allow Keyboard marks (++)
  - pymdownx.mark               # Allow selection marks (==)
  - pymdownx.inlinehilite       # Syntax-highlight inline code
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - attr_list                   # { Annotations }
  - md_in_html                  # Markdown inside HTML
  - def_list                    # Definition lists (Glossary)
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:  
  analytics:
    provider: google
    property:
