site_name: Acceso a Datos
nav:
    - Inicio: index.md
    - 1.- Acceso a datos mediante ficheros [Actualizado Julio 25]: 
      - 1.1.- Gestión de ficheros con Java: ud1/filevsfiles.md
      - 1.2.- Lectura y escritura de ficheros de texto en Java:
        - 1.2.1.- Introducción: ud1/io.md
        - 1.2.2.- Operaciones con ficheros binarios en Java: ud1/binaryfiles.md
        - 1.2.3.- Operaciones con ficheros de caracteres en Java: ud1/13characterfiles.md
      - 1.3.- Ficheros de acceso aleatorio: ud1/16randomaccessfile.md
      - 1.4.- Lectura y escritura de objectos en Java: ud1/22readwriteobjects.md
      - 1.5.- Ficheros de configuración: ud1/17configfiles.md
      - 1.6.- JSON: ud1/19jsonfiles.md
      - 1.7.- Crear un .jar: ud1/20createjar.md
      - 1.8.- try-with-resources: ud1/trywithresources.md
      
    - 2.- Acceso a bases de datos relacionales con JDBC: 
      - 2.1.- Persistencia de la información: ud2/21persistencia.md
      - 2.2.- Desfase objeto-relacional: ud2/22mapeo.md
      - 2.3.- Manejo de conectores - JDBC: ud2/23conectores.md
      - 2.4.- Transacciones: ud2/24transactions.md
      - 2.5.- Procedimientos y funciones almacenadas: ud2/25procedures.md
      - 2.6.- Mejora del rendimiento: ud2/26rendimiento.md
      - 2.7.- Estructura de los proyectos: ud2/27projectstructure.md
    - 3.- ORM con Hibernate y JPA:
      - 3.1.- Herramientas ORM: ud3/31mapeo.md
      - 3.2.- Jakarta - JPA: ud3/32jpa.md
      - 3.3.- Hibernate: ud3/33hibernate.md
      - 3.4.- Patrón DAO: ud3/34dao.md
      - 3.5.- Service Layer: ud3/35service.md
    - 4.- Bases de datos documentales con MongoDB:
      - 4.1.- Introducción: udmongodb/mongodb1.md
    - 5.- Spring Framework:
      - 5.1.- Introducción a Spring Framework: ud4/41introduccionspring.md
      - 5.2.- Spring Data JPA: ud4/42repository.md
      - 5.3.- API REST - Spring Web: ud4/43rest.md
      - 5.4.- @Query y Response: ud4/44queryresponse.md
    - 6.- Java Modules:
      - 6.1.- Módulos en Java: ud5/51modulo.md
    - About : about.md
theme:
  name: material
  language: es
  custom_dir: overrides
  #logo: assets/logo.png
  
  palette:
    - scheme: default
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  
  extra:
    #generator: false
  
  copyright: Copyright &copy; 2021 - Patricia Martí
  
  features:
    - content.code.annotate
    - navitagion.tabs
    #- navigation.sections
    - navigation.top

markdown_extensions:
  - admonition                  # Info boxes (in different colors)
  - codehilite
  - pymdownx.details            # "
  - pymdownx.superfences        # Info boxes, tabs
  - pymdownx.caret              # Allow superscript and insertion marks (^ and ^^)
  - pymdownx.tilde              # Allow subscript and deletion marks (~ and ~~)
  - pymdownx.keys               # Allow Keyboard marks (++)
  - pymdownx.mark               # Allow selection marks (==)
  - pymdownx.inlinehilite       # Syntax-highlight inline code
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - attr_list                   # { Annotations }
  - md_in_html                  # Markdown inside HTML
  - def_list                    # Definition lists (Glossary)
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:  
  analytics:
    provider: google
    property:
